# Generated by Django 5.0 on 2023-12-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_address_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='detailed',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='general',
        ),
        migrations.AddField(
            model_name='mro',
            name='general',
            field=models.TextField(blank=True, null=True, verbose_name='общая инфа'),
        ),
    ]
