# Generated by Django 5.0 on 2023-12-19 07:55

from django.db import migrations
from dictionary_migration import info


def change_names(apps, schema_editor):
    Mro = apps.get_model('retail', 'Mro')
    names = {
        "cheboksarskoe_mro_info": "Чебоксарское МРО",
        'alatyrskoe_mro_info': "Алатырское МРО",
        'batyrevo_mro_info': "Батыревское МРО",
        'kanashskoe_mro_info': "Канашское МРО",
        'novocheboksarskoe_mro_info': "Новочебоксарское МРО",
        'civilskoe_mro_info': "Цивильское МРО",
        'shumerlinskoe_mro_info': "Шумерлинское МРО",
        'yadrinskoe_mro_info': "Ядринское МРО",
        'upravlenie_info': "Управление"
    }
    for key, value in names.items():
        mro_here = Mro.objects.get(name=key)
        mro_here.name = value
        mro_here.save()


class Migration(migrations.Migration):
    dependencies = [
        ('retail', '0006_auto_20231219_1026'),
    ]

    operations = [
        migrations.RunPython(change_names)
    ]
