# Generated by Django 5.0 on 2023-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(blank=True, null=True, verbose_name='общая инфа')),
                ('detailed', models.TextField(blank=True, null=True, verbose_name='детализированная инфа')),
            ],
        ),
    ]
