# Generated by Django 5.0 on 2023-12-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='retail.mro', verbose_name='связь с МРО'),
        ),
    ]
