# Generated by Django 5.0 on 2023-12-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_auto_20231219_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='адрес счета'),
        ),
    ]
