# Generated by Django 5.0 on 2023-12-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0008_bill_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number_and_type_pu',
            field=models.TextField(blank=True, null=True, verbose_name='Номер и тип ПУ'),
        ),
        migrations.AddField(
            model_name='bill',
            name='readings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Показания счетчика'),
        ),
        migrations.AddField(
            model_name='bill',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приёма'),
        ),
    ]
