# Generated by Django 5.0 on 2023-12-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='id_device',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID счетчика'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_indication',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID показания'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_tariff',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID тарифа'),
        ),
    ]
