# Generated by Django 5.0 on 2024-01-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0012_rate_remove_bill_id_indication_remove_bill_id_tariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='retail.bill', verbose_name='ЛС'),
        ),
    ]
