# Generated by Django 5.0 on 2024-01-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0013_rate_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='id_device',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='number_and_type_pu',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='bill',
        ),
        migrations.AddField(
            model_name='rate',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Обозначение'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='адрес счета')),
                ('number_and_type_pu', models.TextField(blank=True, null=True, verbose_name='Номер и тип ПУ')),
                ('id_device', models.IntegerField(blank=True, null=True, verbose_name='ID счетчика')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='retail.bill', verbose_name='Лицевой счет')),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='retail.device', verbose_name='Устройство'),
        ),
    ]
