# Generated by Django 5.0 on 2024-02-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0014_remove_bill_address_remove_bill_id_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_title',
            field=models.TextField(blank=True, null=True, verbose_name='Прибор учета'),
        ),
    ]
