# Generated by Django 5.0 on 2024-02-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0015_device_device_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='modification',
            field=models.TextField(blank=True, null=True, verbose_name='Модификация прибора учета'),
        ),
    ]
