# Generated by Django 5.0 on 2024-02-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0016_device_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.TextField(blank=True, null=True, verbose_name='Серийный номер прибора учета'),
        ),
    ]
