# Generated by Django 5.0 on 2024-02-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0017_device_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
